name: Make List
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 1'
  workflow_dispatch:
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      # clone
      - uses: actions/checkout@v3
        with:
          repository: wsm25/cn-domain-list-gost
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - run: git clone https://github.com/v2fly/domain-list-community --depth=1 && mv domain-list-community domains
      - run: git clone https://github.com/misakaio/chnroutes2 --depth=1 && mv chnroutes2/chnroutes.txt ./cnip.txt && rm -rf chnroutes2
      # make & commit
      - run: python3 ./make.py
      - run: cat cndm.txt
      - run: rm -rf domains
      - run: echo "::set-output name=date::$(date +'%Y-%m-%d')" # get date
        id: date
      - uses: actions-js/push@master
        with:
            github_token: ${{ secrets.ACTIONSECRET }}
            message: Update @ ${{ steps.date.outputs.date }}
      - run: rm -rf ./*
      
          
