name: Make List
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 1'
  workflow_dispatch:
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      # clone
      - uses: actions/checkout@v3
        with:
          name: v2fly/domain-list-community
          path: domains
      - uses: actions/checkout@v3
        with:
          name:  wsm25/cn-domain-list-gost 
          path: main
      - run: cd main
      # make & commit
      - run: python3 ./make.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update list
      # clean
      - run: cd ..
      - run: rm -rf domains main
      
          
