name: Make List
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 1'
  workflow_dispatch:
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      # clone
      - run: rm -rf ./*
      - uses: actions/checkout@v3
        with:
          repository: wsm25/cn-domain-list-gost
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - run: git clone https://github.com/v2fly/domain-list-community --depth=1 && mv domain-list-community domains
      # make & commit
      - run: tree -L 2
      - run: python3 ./make.py
      - run: tree -L 2
      - run: rm -rf domains
      - uses: actions-js/push@master
        with:
            github_token: ${{ secrets.ACTIONSECRET }}
            message: Update cndm.txt @ ${date}
      
          
