name: Make List
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 1'
  workflow_dispatch:
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      # clone
      - run: git clone https://github.com/v2fly/domain-list-community --depth=1 && mv domain-list-community domains
      - uses: actions/checkout@v3
        with:
          name:  wsm25/cn-domain-list-gost 
          path: main
      # make & commit
      - run: tree -L 3
      - run: cd main&&python3 ./make.py
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update list
      # clean
      - run: cd ..
      - run: rm -rf domains main
      
          
