name: Make List
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 1'
  workflow_dispatch:
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      # clone
      - run: git clone https://github.com/v2fly/domain-list-community --depth=1 && mv domain-list-community domains
      - run: git clone https://github.com/wsm25/cn-domain-list-gost  --depth=1 && mv cn-domain-list-gost main
      # make & commit
      - run: tree -L 2
      - run: cd main&&python3 ./make.py
      - run: tree -L 2
      - run: cd main && git add . && git commit -m "Update cndm" && git push
      # clean
      - run: cd ..
      - run: rm -rf domains main
      
          
